

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/20221127_november_boat_db03_ship
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8813


group6:
  shipType:
    shipTypePageSize: 10